# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_entry.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dynobuf.LogEntry" do
    optional :application_id, :string, 1
    optional :process, :string, 2
    optional :timestamp, :int64, 3
    optional :data, :string, 4
  end
end

module Dynobuf
  LogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("dynobuf.LogEntry").msgclass
end
