# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_entry_list.proto

require 'google/protobuf'

require 'log_entry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dynobuf.LogEntryList" do
    optional :application_id, :string, 1
    optional :timestamp, :int64, 2
    repeated :entries, :message, 3, "dynobuf.LogEntry"
  end
end

module Dynobuf
  LogEntryList = Google::Protobuf::DescriptorPool.generated_pool.lookup("dynobuf.LogEntryList").msgclass
end
