# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metric_data_point.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dynobuf.MetricDataPoint" do
    optional :application_id, :string, 1
    optional :process, :string, 2
    optional :cluster, :string, 3
    optional :metric, :string, 4
    optional :operation, :string, 5
    optional :value, :double, 6
    optional :tags, :string, 7
    optional :timestamp, :int64, 8
  end
end

module Dynobuf
  MetricDataPoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("dynobuf.MetricDataPoint").msgclass
end
