# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metric_state.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dynobuf.MetricState" do
    optional :timestamp, :int64, 1
    optional :application_id, :string, 2
    optional :process, :string, 3
    optional :cluster, :string, 4
    optional :metric, :string, 5
    optional :operation, :string, 6
    optional :tags, :string, 7
    optional :num_values, :int64, 8
    optional :sum, :double, 9
    optional :min, :double, 10
    optional :max, :double, 11
    optional :sum_of_squares, :double, 12
  end
end

module Dynobuf
  MetricState = Google::Protobuf::DescriptorPool.generated_pool.lookup("dynobuf.MetricState").msgclass
end
