// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_entry_list.proto

package io.dynomatic.protobuf;

public final class LogEntryListOuterClass {
  private LogEntryListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogEntryListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dynobuf.LogEntryList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    java.util.List<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry> 
        getEntriesList();
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    io.dynomatic.protobuf.LogEntryOuterClass.LogEntry getEntries(int index);
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    java.util.List<? extends io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder> 
        getEntriesOrBuilderList();
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder getEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code dynobuf.LogEntryList}
   */
  public  static final class LogEntryList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dynobuf.LogEntryList)
      LogEntryListOrBuilder {
    // Use LogEntryList.newBuilder() to construct.
    private LogEntryList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogEntryList() {
      entries_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogEntryList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entries_ = new java.util.ArrayList<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entries_.add(
                  input.readMessage(io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dynomatic.protobuf.LogEntryListOuterClass.internal_static_dynobuf_LogEntryList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dynomatic.protobuf.LogEntryListOuterClass.internal_static_dynobuf_LogEntryList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList.class, io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList.Builder.class);
    }

    public static final int ENTRIES_FIELD_NUMBER = 1;
    private java.util.List<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry> entries_;
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    public java.util.List<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry> getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    public java.util.List<? extends io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    public io.dynomatic.protobuf.LogEntryOuterClass.LogEntry getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated .dynobuf.LogEntry entries = 1;</code>
     */
    public io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(1, entries_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList)) {
        return super.equals(obj);
      }
      io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList other = (io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList) obj;

      boolean result = true;
      result = result && getEntriesList()
          .equals(other.getEntriesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getEntriesCount() > 0) {
        hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getEntriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dynobuf.LogEntryList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dynobuf.LogEntryList)
        io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dynomatic.protobuf.LogEntryListOuterClass.internal_static_dynobuf_LogEntryList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dynomatic.protobuf.LogEntryListOuterClass.internal_static_dynobuf_LogEntryList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList.class, io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList.Builder.class);
      }

      // Construct using io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dynomatic.protobuf.LogEntryListOuterClass.internal_static_dynobuf_LogEntryList_descriptor;
      }

      public io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList getDefaultInstanceForType() {
        return io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList.getDefaultInstance();
      }

      public io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList build() {
        io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList buildPartial() {
        io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList result = new io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList(this);
        int from_bitField0_ = bitField0_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList) {
          return mergeFrom((io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList other) {
        if (other == io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList.getDefaultInstance()) return this;
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entries_ = new java.util.ArrayList<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry>(entries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.dynomatic.protobuf.LogEntryOuterClass.LogEntry, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder, io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder> entriesBuilder_;

      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public java.util.List<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public io.dynomatic.protobuf.LogEntryOuterClass.LogEntry getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder setEntries(
          int index, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder setEntries(
          int index, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder addEntries(io.dynomatic.protobuf.LogEntryOuterClass.LogEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder addEntries(
          int index, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder addEntries(
          io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder addEntries(
          int index, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder addAllEntries(
          java.lang.Iterable<? extends io.dynomatic.protobuf.LogEntryOuterClass.LogEntry> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public java.util.List<? extends io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .dynobuf.LogEntry entries = 1;</code>
       */
      public java.util.List<io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.dynomatic.protobuf.LogEntryOuterClass.LogEntry, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder, io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.dynomatic.protobuf.LogEntryOuterClass.LogEntry, io.dynomatic.protobuf.LogEntryOuterClass.LogEntry.Builder, io.dynomatic.protobuf.LogEntryOuterClass.LogEntryOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dynobuf.LogEntryList)
    }

    // @@protoc_insertion_point(class_scope:dynobuf.LogEntryList)
    private static final io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList();
    }

    public static io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogEntryList>
        PARSER = new com.google.protobuf.AbstractParser<LogEntryList>() {
      public LogEntryList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogEntryList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogEntryList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogEntryList> getParserForType() {
      return PARSER;
    }

    public io.dynomatic.protobuf.LogEntryListOuterClass.LogEntryList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dynobuf_LogEntryList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dynobuf_LogEntryList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024log_entry_list.proto\022\007dynobuf\032\017log_ent" +
      "ry.proto\"2\n\014LogEntryList\022\"\n\007entries\030\001 \003(" +
      "\0132\021.dynobuf.LogEntryB\027\n\025io.dynomatic.pro" +
      "tobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.dynomatic.protobuf.LogEntryOuterClass.getDescriptor(),
        }, assigner);
    internal_static_dynobuf_LogEntryList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dynobuf_LogEntryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dynobuf_LogEntryList_descriptor,
        new java.lang.String[] { "Entries", });
    io.dynomatic.protobuf.LogEntryOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
